#!/usr/bin/env python3
"""
publish-repo.py — Publish built extension APKs to the MHRepo repository.

Based on Keiyoushi's publish approach:
  - Reads keiyoushi-source-info.json (generated by Gradle's GenerateSourceInfoTask)
  - Icons served from source repo via jsDelivr (no APK extraction)
  - CDN cache purge after publish
  - Cleanup mode for removing orphaned extensions

Usage:
  python publish-repo.py                    # Publish mode (default)
  python publish-repo.py --cleanup          # Cleanup mode (remove orphaned extensions)
  python publish-repo.py --cleanup --dry    # Cleanup dry-run

Environment variables:
  REPO_PAT    — GitHub PAT for the MHRepo repository (required)
  REPO_OWNER  — Owner of the MHRepo repo (default: marbou92)
  REPO_NAME   — Name of the MHRepo repo (default: MHRepo)
  SOURCE_OWNER — Owner of the source repo (for icon URLs, default: marbou92)
  SOURCE_NAME  — Name of the source repo (default: MHExtensions)
  SIGNING_FINGERPRINT — SHA-256 fingerprint of the signing key (optional, for index metadata)
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# =============================================================================
# Configuration
# =============================================================================

REPO_OWNER = os.environ.get("REPO_OWNER", "marbou92")
REPO_NAME = os.environ.get("REPO_NAME", "MHRepo")
REPO_URL = f"https://x-access-token:{os.environ['REPO_PAT']}@github.com/{REPO_OWNER}/{REPO_NAME}.git"
REPO_DIR = Path("/tmp/MHRepo")
INDEX_FILE = REPO_DIR / "index.json"
REPO_JSON_FILE = REPO_DIR / "repo.json"

SOURCE_OWNER = os.environ.get("SOURCE_OWNER", "marbou92")
SOURCE_NAME = os.environ.get("SOURCE_NAME", "MHExtensions")
SOURCE_ROOT = Path(os.environ.get("GITHUB_WORKSPACE", "."))

# CDN base URLs (matching Keiyoushi's approach)
APK_BASE_URL = f"https://cdn.jsdelivr.net/gh/{REPO_OWNER}/{REPO_NAME}@main/apk"
JAR_BASE_URL = f"https://cdn.jsdelivr.net/gh/{REPO_OWNER}/{REPO_NAME}@main/jar"
ICON_BASE_URL = f"https://cdn.jsdelivr.net/gh/{SOURCE_OWNER}/{SOURCE_NAME}@main"

SIGNING_FINGERPRINT = os.environ.get("SIGNING_FINGERPRINT", "")


# =============================================================================
# Helpers
# =============================================================================

def run(cmd, **kwargs):
    """Run a shell command, exit on failure."""
    result = subprocess.run(cmd, shell=True, **kwargs)
    if result.returncode != 0:
        print(f"ERROR: Command failed: {cmd}", file=sys.stderr)
        sys.exit(1)
    return result


def git(*args, cwd=REPO_DIR):
    """Run a git command in the repo directory."""
    cmd = ["git"] + list(args)
    result = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)
    if result.returncode != 0:
        print(f"git {' '.join(args)} failed:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    return result.stdout.strip()


def get_valid_packages():
    """
    Extract all valid extension package names from settings.gradle.kts.
    Returns a set of full package names like:
      eu.kanade.tachiyomi.extension.all.comixto
      eu.kanade.tachiyomi.extension.en.manhuarmtl
    """
    settings_file = SOURCE_ROOT / "settings.gradle.kts"
    if not settings_file.exists():
        print(f"ERROR: {settings_file} not found", file=sys.stderr)
        sys.exit(1)

    content = settings_file.read_text()
    pattern = re.compile(r'loadIndividualExtension\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)')
    matches = pattern.findall(content)

    packages = set()
    for lang, name in matches:
        packages.add(f"eu.kanade.tachiyomi.extension.{lang}.{name}")

    print(f"Found {len(packages)} valid package(s) in settings.gradle.kts:")
    for pkg in sorted(packages):
        print(f"  - {pkg}")
    return packages


def clone_repo():
    """Clone or pull the MHRepo repository."""
    if REPO_DIR.exists():
        shutil.rmtree(REPO_DIR)
    print(f"Cloning {REPO_OWNER}/{REPO_NAME}...")
    run(f"git clone --depth 1 {REPO_URL} {REPO_DIR}")


def load_index():
    """Load the existing index.json, or return empty structure if it doesn't exist."""
    if not INDEX_FILE.exists():
        return {"info": [], "latest": 0, "blocked": []}
    with open(INDEX_FILE) as f:
        return json.load(f)


def save_index(index):
    """Save index.json with pretty formatting."""
    with open(INDEX_FILE, "w") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)
        f.write("\n")


def purge_cdn_cache():
    """Purge jsDelivr CDN cache for index files (like Keiyoushi does)."""
    files_to_purge = [
        f"https://purge.jsdelivr.net/gh/{REPO_OWNER}/{REPO_NAME}@main/index.json",
        f"https://purge.jsdelivr.net/gh/{REPO_OWNER}/{REPO_NAME}@main/repo.json",
    ]
    for url in files_to_purge:
        try:
            subprocess.run(["curl", "-s", "-o", "/dev/null", url], timeout=30)
            print(f"  Purged CDN: {url}")
        except Exception:
            print(f"  WARNING: Failed to purge {url}")


# =============================================================================
# Cleanup mode
# =============================================================================

def cleanup(dry_run=False):
    """Remove orphaned extensions from MHRepo that no longer exist in MHExtensions."""
    valid_packages = get_valid_packages()

    clone_repo()
    index = load_index()

    if "info" not in index or not isinstance(index["info"], list):
        print("WARNING: index.json has no 'info' array, nothing to clean up")
        return

    original_count = len(index["info"])
    kept_entries = []
    deleted_entries = []

    for entry in index["info"]:
        pkg = entry.get("pkg", "")
        if pkg in valid_packages:
            kept_entries.append(entry)
        else:
            deleted_entries.append(entry)

    if not deleted_entries:
        print("No orphaned extensions found. Nothing to clean up.")
        return

    print(f"\nFound {len(deleted_entries)} orphaned extension(s) to remove:")
    for entry in deleted_entries:
        pkg = entry.get("pkg", "?")
        name = entry.get("name", "?")
        print(f"  - {name} ({pkg})")

    if dry_run:
        print("\n[DRY RUN] No files were deleted. Re-run without --dry to actually delete.")
        return

    # Delete APK and icon files for orphaned entries
    for entry in deleted_entries:
        for field in ["apk", "icon"]:
            rel_path = entry.get(field, "")
            if not rel_path:
                continue
            # Strip CDN prefix if present
            if rel_path.startswith("http"):
                if "@main/" in rel_path:
                    rel_path = rel_path.split("@main/")[-1]
                else:
                    rel_path = rel_path.split("/main/")[-1]
            file_path = REPO_DIR / rel_path
            if file_path.exists():
                file_path.unlink()
                print(f"  Deleted file: {rel_path}")
            else:
                print(f"  File not found (skipped): {rel_path}")

    # Update index
    index["info"] = kept_entries
    save_index(index)

    print(f"\nCleanup complete: {original_count} → {len(kept_entries)} entries")

    # Commit and push
    git("add", "-A", cwd=REPO_DIR)
    status = git("status", "--porcelain", cwd=REPO_DIR)
    if not status:
        print("No changes to commit.")
        return

    commit_msg = "chore: cleanup orphaned extensions\n\nRemoved:\n"
    for entry in deleted_entries:
        commit_msg += f"- {entry.get('name', '?')} ({entry.get('pkg', '?')})\n"

    git("commit", "-m", commit_msg, cwd=REPO_DIR)
    git("push", cwd=REPO_DIR)
    purge_cdn_cache()
    print("Pushed cleanup commit to MHRepo.")


# =============================================================================
# Publish mode (Keiyoushi-style: read keiyoushi-source-info.json)
# =============================================================================

def find_source_info_files():
    """
    Find all keiyoushi-source-info.json files generated by the Gradle build.
    These are emitted by GenerateSourceInfoTask into each module's build dir.
    Works with both local builds and downloaded CI artifacts.
    """
    info_files = []
    for root, dirs, files in os.walk(SOURCE_ROOT):
        if ".gradle" in root or "intermediates" in root:
            continue
        for f in files:
            if f == "keiyoushi-source-info.json":
                info_files.append(Path(root) / f)
    return info_files


def find_apk_for_info(info_file):
    """
    Find the release APK for a given keiyoushi-source-info.json file.
    Searches in nearby directories (handles both local and artifact layouts).
    """
    build_dir = info_file.parent

    # Try standard Gradle layout: build/outputs/apk/release/*.apk
    apk_dir = build_dir / "outputs" / "apk" / "release"
    if apk_dir.exists():
        apks = list(apk_dir.glob("*.apk"))
        if apks:
            return apks[0]

    # Fallback: search upward and nearby for any release APK matching the module
    # (handles cases where artifact download flattens directory structure)
    info = json.load(open(info_file))
    module = info.get("module", "")
    search_dirs = [build_dir, build_dir.parent, SOURCE_ROOT / "artifacts"]
    for search_dir in search_dirs:
        if search_dir.exists():
            for apk in search_dir.rglob(f"tachiyomi-{module}-v*-release.apk"):
                return apk
            # Also try without -release suffix
            for apk in search_dir.rglob(f"tachiyomi-{module}-v*.apk"):
                return apk

    return None


def find_jar_for_info(info_file):
    """
    Find the release JAR for a given keiyoushi-source-info.json file.
    """
    build_dir = info_file.parent

    # Try standard Gradle layout: build/outputs/jar/release/*.jar
    jar_dir = build_dir / "outputs" / "jar" / "release"
    if jar_dir.exists():
        jars = list(jar_dir.glob("*.jar"))
        if jars:
            return jars[0]

    # Fallback: search for matching JAR
    info = json.load(open(info_file))
    module = info.get("module", "")
    search_dirs = [build_dir, build_dir.parent, SOURCE_ROOT / "artifacts"]
    for search_dir in search_dirs:
        if search_dir.exists():
            for jar in search_dir.rglob(f"tachiyomi-{module}-v*.jar"):
                return jar

    return None


def get_icon_url(module, theme):
    """
    Get the icon URL from the source repo (Keiyoushi approach).
    Priority:
      1. src/{module-as-path}/res/mipmap-xhdpi/ic_launcher.png
      2. lib-multisrc/{theme}/res/mipmap-xhdpi/ic_launcher.png (multisrc fallback)
      3. core/src/main/res/mipmap-xhdpi/ic_launcher.png (default)
    """
    # module is like "all.comixto" or "en.manhuarmtl"
    module_path = module.replace(".", "/")
    icon_path = f"src/{module_path}/res/mipmap-xhdpi/ic_launcher.png"
    full_path = SOURCE_ROOT / icon_path
    if full_path.exists():
        return f"{ICON_BASE_URL}/{icon_path}"

    # Multisrc theme fallback
    if theme:
        theme_path = f"lib-multisrc/{theme}/res/mipmap-xhdpi/ic_launcher.png"
        full_theme_path = SOURCE_ROOT / theme_path
        if full_theme_path.exists():
            return f"{ICON_BASE_URL}/{theme_path}"

    # Default icon
    default_path = "core/src/main/res/mipmap-xhdpi/ic_launcher.png"
    if (SOURCE_ROOT / default_path).exists():
        return f"{ICON_BASE_URL}/{default_path}"

    return None


def content_warning_to_nsfw(cw_int):
    """Convert contentWarning int (0-3) to nsfw boolean."""
    # 0=UNSPECIFIED, 1=SAFE, 2=MIXED, 3=NSFW
    return cw_int >= 2


def content_warning_to_string(cw_int):
    """Convert contentWarning int to readable string."""
    return {0: "SAFE", 1: "SAFE", 2: "MIXED", 3: "NSFW"}.get(cw_int, "SAFE")


def publish():
    """Publish built extensions to MHRepo using keiyoushi-source-info.json."""
    clone_repo()
    index = load_index()

    # Find all keiyoushi-source-info.json files
    info_files = find_source_info_files()
    if not info_files:
        print("No keiyoushi-source-info.json files found.")
        print("Did you run 'assembleRelease'? The Gradle build should generate these.")
        sys.exit(1)

    print(f"\nFound {len(info_files)} extension(s) to publish:")
    for info_file in info_files:
        print(f"  - {info_file}")

    # Index lookup by package name for easy update
    info_by_pkg = {e.get("pkg"): e for e in index.get("info", [])}

    published_count = 0

    for info_file in info_files:
        with open(info_file) as f:
            meta = json.load(f)

        pkg = meta["packageName"]
        name = meta["name"]
        code = meta["versionCode"]
        version = meta["versionName"]
        module = meta["module"]
        theme = meta.get("theme")
        sources = meta.get("sources", [])
        content_warning = meta.get("contentWarning", 1)

        # Find the APK
        apk_path = find_apk_for_info(info_file)
        if apk_path is None:
            print(f"\n  WARNING: No release APK found for {name} ({pkg}), skipping")
            continue

        # Find the JAR (optional — if signing is configured)
        jar_path = find_jar_for_info(info_file)

        print(f"\n  Publishing {name} ({pkg}) v{version} (code {code})...")

        # Ensure apk/ and jar/ directories exist
        apk_dir = REPO_DIR / "apk"
        jar_dir = REPO_DIR / "jar"
        apk_dir.mkdir(exist_ok=True)
        jar_dir.mkdir(exist_ok=True)

        # Copy APK to repo/apk/
        apk_filename = apk_path.name
        apk_dest = apk_dir / apk_filename
        shutil.copy2(apk_path, apk_dest)

        # Copy JAR to repo/jar/ (if exists)
        jar_filename = None
        if jar_path:
            jar_filename = jar_path.name
            jar_dest = jar_dir / jar_filename
            shutil.copy2(jar_path, jar_dest)

        # Get icon URL from source repo (Keiyoushi approach — no APK extraction)
        icon_url = get_icon_url(module, theme)

        # Build index entry
        entry = {
            "name": name,
            "pkg": pkg,
            "apk": f"{APK_BASE_URL}/{apk_filename}",
            "lang": sources[0]["lang"] if sources else "all",
            "code": code,
            "version": version,
            "nsfw": content_warning_to_nsfw(content_warning),
            "hasUpdate": True,
            "hasReadme": False,
            "hasChangelog": False,
            "sources": [
                {
                    "name": s["name"],
                    "lang": s["lang"],
                    "id": s["id"],
                    "baseUrl": s["baseUrl"],
                }
                for s in sources
            ],
        }

        if icon_url:
            entry["icon"] = icon_url

        if jar_filename:
            entry["jar"] = f"{JAR_BASE_URL}/{jar_filename}"

        # Remove old APKs/JARs for this package (cleanup of previous versions)
        module_suffix = module  # e.g., "en.manhuarmtl"
        for old_file in apk_dir.glob(f"tachiyomi-{module_suffix}-v*.apk"):
            if old_file.name != apk_filename:
                old_file.unlink()
                print(f"    Removed old APK: {old_file.name}")
        if jar_filename:
            for old_file in jar_dir.glob(f"tachiyomi-{module_suffix}-v*.jar"):
                if old_file.name != jar_filename:
                    old_file.unlink()
                    print(f"    Removed old JAR: {old_file.name}")

        # Update or add entry
        info_by_pkg[pkg] = entry
        published_count += 1
        print(f"    Updated index entry for {pkg}")

    if published_count == 0:
        print("\nNo extensions were published.")
        return

    # Rebuild info array (preserve order, add new entries at end)
    existing_pkgs = {e.get("pkg") for e in index.get("info", [])}
    new_info = []
    for entry in index.get("info", []):
        pkg = entry.get("pkg")
        if pkg in info_by_pkg:
            new_info.append(info_by_pkg[pkg])
    # Add new entries
    for pkg, entry in info_by_pkg.items():
        if pkg not in existing_pkgs:
            new_info.append(entry)

    index["info"] = new_info
    save_index(index)

    # Ensure repo.json exists (static pointer for Mihon)
    if not REPO_JSON_FILE.exists():
        repo_json = {
            "index_v2": f"https://raw.githubusercontent.com/{REPO_OWNER}/{REPO_NAME}/main/index.json",
            "meta": {
                "name": "MHExtensions",
                "website": f"https://github.com/{SOURCE_OWNER}/{SOURCE_NAME}",
            },
        }
        if SIGNING_FINGERPRINT:
            repo_json["meta"]["signingKeyFingerprint"] = SIGNING_FINGERPRINT
        with open(REPO_JSON_FILE, "w") as f:
            json.dump(repo_json, f, indent=2)
            f.write("\n")
        print(f"\nCreated repo.json")

    # Commit and push
    git("add", "-A", cwd=REPO_DIR)
    status = git("status", "--porcelain", cwd=REPO_DIR)
    if not status:
        print("\nNo changes to commit.")
        return

    git("commit", "-m", f"chore: publish {published_count} extension(s)", cwd=REPO_DIR)
    git("push", cwd=REPO_DIR)

    # Purge CDN cache (like Keiyoushi does)
    print("\nPurging CDN cache...")
    purge_cdn_cache()

    print(f"\nPublished {published_count} extension(s) to MHRepo.")


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="Publish extensions to MHRepo")
    parser.add_argument(
        "--cleanup",
        action="store_true",
        help="Remove orphaned extensions from MHRepo that no longer exist in MHExtensions",
    )
    parser.add_argument(
        "--dry",
        action="store_true",
        help="Dry run (only used with --cleanup): list what would be deleted without deleting",
    )
    args = parser.parse_args()

    if "REPO_PAT" not in os.environ:
        print("ERROR: REPO_PAT environment variable is required", file=sys.stderr)
        sys.exit(1)

    if args.cleanup:
        cleanup(dry_run=args.dry)
    else:
        publish()


if __name__ == "__main__":
    main()
